services:
  db-django:
    image: postgres
    volumes:
      - ./app/data/db-django:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
<<<<<<< HEAD
  django:
    build: .
=======
  web:
    build: .
    container_name: web
>>>>>>> 9a5ef340f086152afa9757715e8b004c14f396dd
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py makemigrations todo &&
        python manage.py makemigrations accounts &&
        python manage.py migrate &&
        python telegram/bot.py
        python manage.py runserver 0.0.0.0:8000 &&
      "
    volumes:
<<<<<<< HEAD
      - ./app:/code/
=======
      - ./app/:/app/
>>>>>>> 9a5ef340f086152afa9757715e8b004c14f396dd
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
<<<<<<< HEAD
      - db-django
=======
      - db
>>>>>>> 9a5ef340f086152afa9757715e8b004c14f396dd
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db-django
    restart: always
