version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - .app/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_ENGINE=django.db.backends.postgresql_psycopg2
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    container_name: web
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py makemigrations todo &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
