FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code/aiogram

COPY requirements-aiogram.txt /code/aiogram
RUN pip install -r requirements-aiogram.txt

COPY /app/aiogram /code/aiogram