FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code/django

COPY requirements-django.txt /code/django
RUN pip install -r requirements-django.txt

COPY /app/django /code/django
