# Generated by Django 3.2.19 on 2023-06-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('created_at',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
